# Spring application name
spring.application.name=location-app

spring.datasource.url=jdbc:postgresql://localhost:5432/locationbasedb
spring.datasource.username=nyeinsusuthwin
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=MySuperSecretKey1234567890123456
app.jwt.expiration-ms=86400000

app.geoapify.key=2bca90095f1b4e05830856057d52e4a1



stripe.secret.key=YOUR_SECRET_KEY
stripe.publishable.key=pk_test_51TH7ijEh8s8OJaKqPM7XvWwSjlzdPVSYFBP3EJ9ce1YDI7XNkZMoDoBoItHQAng8eAV86CmV5bhqUz0ehfs0w9Nq00JXAwocOH
stripe.webhook.secret=whsec_607c41ae3970af197f392c104682eb32c3f44196bd896f7bd375111bc65512d9
stripe.premium.price.id=price_1TH7kPEh8s8OJaKqqI4SIuKJ
app.frontend.url=http://localhost:5173

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thwinsusu08@gmail.com
spring.mail.password=dahr eijr pfdq kkat
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.base.url=http://localhost:5173