# Spring application name
spring.application.name=location-app

spring.datasource.url=jdbc:postgresql://localhost:5432/locationbasedb
spring.datasource.username=nyeinsusuthwin
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=MySuperSecretKey1234567890123456
app.jwt.expiration-ms=86400000

app.overpass.url = https://overpass-api.de/api/interpreter
app.opentripmap.url=https://api.opentripmap.com/0.1/en/places
app.opentripmap.key=PUT_YOUR_OPENTRIPMAP_KEY_HERE